// Mocks generated by Mockito 5.0.14 from annotations
// in weather_app/test/features/location/usecases/search_adress_usecase_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/features/location/domain/entities/address.dart'
    as _i3;
import 'package:weather_app/features/location/domain/entities/address_component.dart'
    as _i4;
import 'package:weather_app/features/location/domain/entities/geometry.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeGeometry_0 extends _i1.Fake implements _i2.Geometry {}

/// A class which mocks [Address].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddress extends _i1.Mock implements _i3.Address {
  MockAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.AddressComponent> get addressComponents =>
      (super.noSuchMethod(Invocation.getter(#addressComponents),
          returnValue: <_i4.AddressComponent>[]) as List<_i4.AddressComponent>);
  @override
  String get formmatedAddress =>
      (super.noSuchMethod(Invocation.getter(#formmatedAddress), returnValue: '')
          as String);
  @override
  _i2.Geometry get geometry => (super.noSuchMethod(Invocation.getter(#geometry),
      returnValue: _FakeGeometry_0()) as _i2.Geometry);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  String toString() => super.toString();
}
