name: Dart CI

on: [pull_request,push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter action
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter upgrade
      
      - name : Get dependencie
        run : flutter pub get
        
      - name : Flutter format
        run :  flutter format --set-exit-if-changed
        
      - name : Analyze Flutter
        run : flutter analyzet  
        
      - name : Testing
        run : flutter test
